[package]
name = "rp2350-rust-template"
version = "0.1.0"
edition = "2024"

publish = false

[dependencies]

embassy-executor = { version = "*", features = ["defmt"] }
embassy-rp = { version = "*", features = ["defmt", "time-driver", "critical-section-impl", "rp235xa", "binary-info", "executor-thread"] }
embassy-time = { version = "*", features = ["defmt", "defmt-timestamp-uptime"] }

cortex-m-rt = "*"

defmt = "*"
defmt-rtt ="*"
panic-probe = { version = "*", features = ["print-defmt"] }
